### ISSUE TITLE
when i click on board scene there are 2 missing prefabs

### ISSUE THREAD

**Issue by francescovigot** [ErkrodC/UnityChess#11]
hello
when i click on board scene there are 2 missing prefabs what are they?
https://imgur.com/a/GHCwgve

**Comment by ErkrodC** [comment]
They are the GameManager and Board prefabs, I'll have to look later why they're dropped from the scene, thanks for letting me know.

E: Both are set at origin.

**Comment by francescovigot** [comment]
i dont know why i cant drag GameManeger and board prefabs on hierarchy
it has no cameras rendering error

**Comment by ErkrodC** [comment]
Did you clone the project or download a zip of the project? To properly clone, download and install Git LFS: https://git-lfs.github.com/

**Comment by francescovigot** [comment]
I downloaded the zip

**Comment by ErkrodC** [comment]
You'll need to clone the project after you install git lfs. Getting a zip isn't going to work because GitHub doesn't yet support getting lfs files via zip download.
